/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap
 * Method:    natDelete
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap_natDelete
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap
 * Method:    natRemove
 * Signature: (JJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap_natRemove
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap
 * Method:    natSet
 * Signature: (JJJ[BIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap_natSet
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray, jint, jint, jboolean);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap
 * Method:    natPut
 * Signature: (JJJ[BIIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap_natPut
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap_Builder */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap_Builder
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMap_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
 * Method:    natInit
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_natInit
  (JNIEnv *, jclass, jclass);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
 * Method:    natLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_natLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
 * Method:    natCompressedLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_natCompressedLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
 * Method:    natGet
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_natGet
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
 * Method:    natGetAsByteBuffer
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_natGetAsByteBuffer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
 * Method:    natGetIntoPreallocated
 * Signature: (JJ[BI)I
 */
JNIEXPORT jint JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_natGetIntoPreallocated
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
 * Method:    natGetRegion
 * Signature: (JJII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_natGetRegion
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView
 * Method:    natGetField
 * Signature: (JJIBB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_natGetField
  (JNIEnv *, jclass, jlong, jlong, jint, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_PrimitiveLongKeyOffHeapMapEntry */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_PrimitiveLongKeyOffHeapMapEntry
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_PrimitiveLongKeyOffHeapMapEntry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_PrimitiveLongKeyOffHeapMapEntryIterator */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_PrimitiveLongKeyOffHeapMapEntryIterator
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_PrimitiveLongKeyOffHeapMapEntryIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_PrimitiveLongKeyOffHeapMapEntryIterator
 * Method:    natIterate
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapMapView_00024PrimitiveLongKeyOffHeapMapEntryIterator_natIterate
  (JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex
 * Method:    natIndexCreate
 * Signature: (JJJI[B)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex_natIndexCreate
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jbyteArray);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex
 * Method:    natIndexDelete
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex_natIndexDelete
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex
 * Method:    natIndexUpdate
 * Signature: (JJJII[B)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex_natIndexUpdate
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex_Builder */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex_Builder
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndex_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView
 * Method:    natInit
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_natInit
  (JNIEnv *, jclass, jclass);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView
 * Method:    natIndexGetKey
 * Signature: (JI[B)J
 */
JNIEXPORT jlong JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_natIndexGetKey
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_PrimitiveLongKeyOffHeapMapEntryIterator */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_PrimitiveLongKeyOffHeapMapEntryIterator
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_PrimitiveLongKeyOffHeapMapEntryIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_PrimitiveLongKeyOffHeapMapEntryIterator
 * Method:    natIterateStart
 * Signature: (JI[B)J
 */
JNIEXPORT jlong JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_00024PrimitiveLongKeyOffHeapMapEntryIterator_natIterateStart
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_PrimitiveLongKeyOffHeapMapEntryIterator
 * Method:    natIterate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_00024PrimitiveLongKeyOffHeapMapEntryIterator_natIterate
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_IndexIterable */

#ifndef _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_IndexIterable
#define _Included_de_jpaw_offHeap_PrimitiveLongKeyOffHeapIndexView_IndexIterable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_AbstractOffHeapMap */

#ifndef _Included_de_jpaw_offHeap_AbstractOffHeapMap
#define _Included_de_jpaw_offHeap_AbstractOffHeapMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jpaw_offHeap_AbstractOffHeapMap
 * Method:    natGetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_jpaw_offHeap_AbstractOffHeapMap_natGetSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_jpaw_offHeap_AbstractOffHeapMap
 * Method:    natFullDump
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_AbstractOffHeapMap_natFullDump
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_jpaw_offHeap_AbstractOffHeapMap
 * Method:    natGetHistogram
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_de_jpaw_offHeap_AbstractOffHeapMap_natGetHistogram
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     de_jpaw_offHeap_AbstractOffHeapMap
 * Method:    natOpen
 * Signature: (IIZ)J
 */
JNIEXPORT jlong JNICALL Java_de_jpaw_offHeap_AbstractOffHeapMap_natOpen
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     de_jpaw_offHeap_AbstractOffHeapMap
 * Method:    natGetView
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jpaw_offHeap_AbstractOffHeapMap_natGetView
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_jpaw_offHeap_AbstractOffHeapMap
 * Method:    natClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_AbstractOffHeapMap_natClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_jpaw_offHeap_AbstractOffHeapMap
 * Method:    natClear
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_AbstractOffHeapMap_natClear
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_jpaw_offHeap_AbstractOffHeapMap
 * Method:    natWriteToFile
 * Signature: (J[BZ)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_AbstractOffHeapMap_natWriteToFile
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean);

/*
 * Class:     de_jpaw_offHeap_AbstractOffHeapMap
 * Method:    natReadFromFile
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_AbstractOffHeapMap_natReadFromFile
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_jpaw_offHeap_OffHeapTransaction */

#ifndef _Included_de_jpaw_offHeap_OffHeapTransaction
#define _Included_de_jpaw_offHeap_OffHeapTransaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natCreateTransaction
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natCreateTransaction
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natSetMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natSetMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natBeginTransaction
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natBeginTransaction
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natCommit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natCommit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natCommitDelayedUpdate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natCommitDelayedUpdate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natUpdateViews
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natUpdateViews
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natRollback
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natRollback
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natSetSafepoint
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natSetSafepoint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natCloseTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natCloseTransaction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jpaw_offHeap_OffHeapTransaction
 * Method:    natDebugRedoLog
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jpaw_offHeap_OffHeapTransaction_natDebugRedoLog
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
